### ISSUE TITLE
[NUKE] Cryptomatte node not entirely working

### ISSUE THREAD

**Issue by NinjaInTheAttic** [Psyop/Cryptomatte#102]
Hello,
When I hook up a cryptomatte node to my .exr file I cannot see my cryptomatte (black screen). Nothing comes up in my Layer Selection either.
-If I hit the 'Force Update' button on the Psyop Cryptomatte tab nothing happens. 
-If I go to the Advanced tab and hit 'Force Update All' then I can see my cryptomatte and I get 'crypto-object' in the Layer selection (nothing else appears when I use the drop down arrow though). I can select a color with the color picker but no alpha mattes are generated.
-If I hit 'Unload Manifest' it does extract all of the mattes with proper naming. They all have alphas and are working correctly.

I'm working with Nuke 10.0v4 on Windows 7. Hopefully this is enough information to diagnose the problem. If anymore information is needed I'll happily give it. 
  
Thanks

**Comment by NinjaInTheAttic** [comment]
Sorry, I should add that this is happening both my my render out of arnold and the sample bunny matte.

**Comment by jonahfriedman** [comment]
Thanks for your report, sorry for the slow response. I'm not sure what's going wrong, I haven't seen these issues before. 

In the Advanced tab of Cryptomatte is a troubleshoot button that checks for installation issues. Can you press that and see what happens? 

Also, are you using the latest version?

**Comment by NinjaInTheAttic** [comment]
Thanks for the response. When you mentioned an older version I had our IT guy do some digging and apparently the was an older version buried on our network. I removed it and installed the current version. It works as advertised now. Thanks!!

**Comment by jonahfriedman** [comment]
Thank you, and sorry again for the slow response!
