### ISSUE TITLE
[NUKE] Cryptomatte Gizmo not working properly with stereo renders

### ISSUE THREAD

**Issue by marcomeyerVFX** [Psyop/Cryptomatte#103]
Hi,
We just noticed that the Cryptomatte gizmo is having a hard time properly picking up the metadata when using Read nodes with the "%V" placeholder for stereo views in a stereo comp.
Updating all calls to `nuke.Node().metadata()` to `nuke.Node().metadata(view=nuke.thisView())` solves this and works as expected again also for non stereo.

(Nuke 11.2)

**Comment by jonahfriedman** [comment]
Thanks for this, it should be fixed in the just released bug fix version, 1.2.4.
