### ISSUE TITLE
[Nuke]  Crypomatte Gizmo: Display version in property bin

### ISSUE THREAD

**Issue by sjkosinski** [Psyop/Cryptomatte#106]
Hello,
More a request than an issue bu would it be possible to display the version the cryptomatte gizmo?

That would make it easier to determine if a script uses the latest one or not.

Thank you,

**Comment by jonahfriedman** [comment]
I think this is a very good suggestion. I'll look into the best way to do. I assume we want the following properties: 

- Visible for a user
- Queriable from a script.

**Comment by jonahfriedman** [comment]
![image](https://user-images.githubusercontent.com/6717262/71371470-207a4f80-2566-11ea-927f-e50247038656.png)

Not the prettiest thing in the world, but fits the bill. Also added a test that the Python version and Gizmo versions (Encryptomatte and Cryptomatte) are the same.

**Comment by sjkosinski** [comment]
Nice! Thank you very much.
Happy Holidays.
