### ISSUE TITLE
cryptomatte problem

### ISSUE THREAD

**Issue by kalyanj211** [Psyop/Cryptomatte#122]
Hi sir,
i am having cryptomatte problem in redshift maya.
autodesk maya 2018
redshift: 2.6.41

![cryptomatte_problem](https://user-images.githubusercontent.com/58654024/70387758-13d6f280-19cf-11ea-81b2-c5374798e6ce.jpg)

**Comment by jonahfriedman** [comment]
Hi Kalyan,

I would ask the Redshift folks for support on this. If it is something in Nuke or Fusion, please feel free to reopen.
