### ISSUE TITLE
Picker doesn't work with missing manifest

### ISSUE THREAD

**Issue by daaims** [Psyop/Cryptomatte#124]
Hi,

Since version 1.2.4 colors aren't pickable in nuke. After some investigation, it seems that cryptomatte need manifests to work. That was not the case in version 1.2.3 and under. 

In nuke, I copied the metadata from an image having the manifest to an image which doesn't have and then I edited the manifest metadata and set {} as value for each manifest keys and it worked.

It seems that cryptomatte doesn't initialize itself correctly when the manifest is missing.

Cheers

**Comment by jonahfriedman** [comment]
Hi @daaims, thanks for the report. Can you share an EXR file that reproduces the problem? 

I can confirm the intention is that a manifest is not required (though metadata is).

**Comment by jonahfriedman** [comment]
Nevermind, I can reproduce pretty easily by removing the manifest from the metadata.

**Comment by jonahfriedman** [comment]
This is fixed in 1.2.6 (and 1.3.0-beta2). Thanks!

**Comment by daaims** [comment]
Great. Thank you !
