### ISSUE TITLE
Cryptomatte node not reading Cryptomatte passes

### ISSUE THREAD

**Issue by GilesJacksonHicks** [Psyop/Cryptomatte#131]
Hi, 

I have installed the Cryptomatte from Github, it apears in my menu toolbar as normal and opens as normal when I select it, however it does not read the rendered out cryptomatte passes, just a blank black screen, a friend tried the same passes with his cryptomatte and it worked fine, so not sure what I've done wrong in the download phase. 

Any help would be greatly appreciated as using this tool for job. 

Thanks

G

**Comment by cedricduriau** [comment]
Hi @GilesJacksonHicks 

Which software are you working in?

Cheers
Cedric

**Comment by GilesJacksonHicks** [comment]
Hi Cedric, 

I completely forgot about this question I wrote, it's been so long :)

Thank you for getting back to me though. 

I'm working in NukeX 12.2

Cheers

G

**Comment by jonahfriedman** [comment]
Closing this since i think it's no longer relevant. Sorry for being so slow to respond to it.
