### ISSUE TITLE
Use Builtin SeparatorControl

### ISSUE THREAD

**Issue by xmnr0x23** [Psyop/Cryptomatte#136]
https://github.com/Psyop/Cryptomatte/blob/36d08c8012bfe0aae67f47358125c0f7a13c4117/fusion/Fuses/Matte/cryptomatte.fuse#L25

We could replace this with a SeparatorControl (apparently that InputControl does exist)

    InSeparator1 = self:AddInput("Separator1" , "Separator1" , {
        INPID_InputControl = "SeparatorControl",
        IC_Visible = true,
        INP_External = false,
    })

**Comment by cedricduriau** [comment]
Hi Kristof

Nice and easy, I can see to replace this. Keep you posted.

Cheers
Cedric

**Comment by cedricduriau** [comment]
Fixed in https://github.com/cedricduriau/Cryptomatte/pull/11
