### ISSUE TITLE
Support sidecar manifests (Was: Question about "manif_file")

### ISSUE THREAD

**Issue by vkoylazov** [Psyop/Cryptomatte#14]
Hello,

I can't find any reference to the "manif_file" string anywhere in the Cryptomatte sources; it is present only in the specification .rtf file. Is this option supported, or deprecated? Originally I intended to implement it, but I removed the implementation after I realized it's not really used anywhere.

Best regards,
Vlado

**Comment by jonahfriedman** [comment]
We added this to the standard with the intention of supporting it, but haven't gotten around to putting it into our Arnold implementation. Now that we have other renderer implementations we'll prioritize getting this working in our Nuke Implementation as soon as possible.

**Comment by vkoylazov** [comment]
Ok, thanks. I will hold the output implementation in V-Ray until it is supported and I can test it.

Best regards,
Vlado

**Comment by jonahfriedman** [comment]
I pushed up a dev branch, called `sidecar_manifest`, with basic sidecar manifest support, and example image with a sidecar manifest. It also has minor corrections to the specification regarding this - should have a sidecar path like "../manifest.json" and not "./manifest.json"  as was stated in there previously.

**Comment by jonahfriedman** [comment]
@cedricduriau I think it'd be a good idea to enable this in the fusion plugin too. In Nuke it was pretty easy as the metadata contained the file path, and after that it's simple to get the relative file path.

**Comment by cedricduriau** [comment]
Hi Jonah

So if I get this right, there is a var being populated by the shader in the EXR metadata holding a cached manifest? If so, this could mean some serious improvements and how does this react on multi frame based manifests? More id sublevels?

Cheers
Cedric

**Comment by jonahfriedman** [comment]
That's right, yeah. Instead of writing the manifest to the EXR header, the renderer implementation can instead write the manifest to a sidecar file, which is a json file. Potentially this could be a single file for a whole sequence, which is an improvement. It could even be a single file for a whole project, the decoder doesn't really care, it's just a path to a file. 

The path to it can be absolute ("c:/path/to/manifest.json") or relative to the EXR file ("../manifest.1001.json"). I think relative paths will be far more useful. 

With regex-based cryptomattes, you need to either freeze the selection or consult the manifest on each frame, so having a single shared manifest for an image sequence would be good to avoid constantly rebuilding it. However I wouldn't count on having renderers spitting out shared manifests like this soon, since having a combined manifest for a whole image sequence could potentially go beyond renderer implementation and involve render farm software as well.

**Comment by cedricduriau** [comment]
Alright, thanks for the info. I know already that Lua has no direct relative path resolving so I'll have to do the resolving myself. Shared manifests would be amazing, but I see your point.

I'll keep you posted.

Cheers
Cedric

**Comment by jonahfriedman** [comment]
We've proposed a change to the sidecar manifests schema to simply and narrow it down to (what we consider to be) the only useful case, and update spec and the implementation in the sidecar_manifests branch. I hope this doesn't cause any issues. I've updated the implementation, the spec, and the examples.

**Comment by jonahfriedman** [comment]
The change is in, sidecar manifests will now be supported by the Nuke plugin (and hopefully soon for the Fusion plugin, but we can create a separate issue for that), and the specification has been updated to reflect the changes. .

**Comment by herronelou** [comment]
@vkoylazov did you ever get to implementing sidecar manifests in Vray? Cryptomatte metadata in EXRs is killing our read performance on the EXRs with some very complex scenes, but can't find an option to sidecar the manifest in Vray Maya.

**Comment by vkoylazov** [comment]
Hi Erwan,

No, we didn't get to implementing it. I tried to find out if we should
write one sidecar per EXR, or somehow combine the data from several/all
frames but I didn't get any feedback.

Even if we did this, wouldn't the speed be exactly the same, no matter if
Nuke itself was reading the metadata or the Cryptomatte plugin?

Best regards,
Vlado

**Comment by herronelou** [comment]
Hi Vlado thanks for the quick reply.

I need to contact Foundry as well, it seems like Nuke constantly accesses
either the metadata or the EXR headers and in our case the cryptomatte data
is magnitudes larger than all the other metadata combined. Somehow it
accesses these even when not using the data at all, whereas with the
sidecars it only accesses these when needed.

In the past (it's been a few years at another company) Renderman was only
able to output one sidecar per frame, and as part of an abandoned tweak I
was working on (#79) I had written a tool to iterate through all the
manifests and combine them into a single one, so if VRay offered that
option that would be amazing, though I suppose there are some choices to be
made (do you put the whole scene in the manifest? Only the visible objects?
If only the visible ones, what about those that go in and out of frame but
you're not rendering all the frames at once?).
I personally quite like the idea of having the whole scene in the manifest
as it can help with Sequence level work as well, to easily make a template
that will select the same objects in every shot no matter what is visible,
but that could increase the size of the manifest.

**Comment by herronelou** [comment]
I have done more tests today, including extracting the metadata to a sidecar using OIIO, and the performance difference is night and day. I've sent a recording to Foundry to show them the issue, it's something with Nuke itself. They already have a bug in their tracker: https://support.foundry.com/hc/en-us/articles/210142389-ID-228821-Reading-in-EXRs-with-a-lot-of-metadata-causes-very-slow-performance-when-changing-frames-in-Nuke 

Seeing as this bug has been filed years ago, I have little hope that it will be solved anytime soon. @vkoylazov do you think sidecars is something that you guys could look into? Thanks a lot.

**Comment by vkoylazov** [comment]
Yes, for sure we can look into it; it's not that complicated to implement
it per file. Do you have recommendation on how the sidecar file should be
named? The same name as the .exr but with .json extension?

Best regards,
Vlado

**Comment by herronelou** [comment]
I haven't put too much thought into it, but that sounds like a reasonable default. I imagine some users would want to be able to define their own path/filename.
Thanks!
