### ISSUE TITLE
[Fusion 17] Getting error when connecting EXR into the node input

### ISSUE THREAD

**Issue by tinogithub** [Psyop/Cryptomatte#143]
Hello,

there is an error I get when piping an EXR into the Cryptomatte-Node.

`...s/Cryptomatte-master/fusion/Fuses/Matte/cryptomatte.fuse:259: attempt to call field 'log_info' (a nil value)
stack traceback:
	...s/Cryptomatte-master/fusion/Fuses/Matte/cryptomatte.fuse:259: in function <...s/Cryptomatte-master/fusion/Fuses/Matte/cryptomatte.fuse:251>
Cryptomatte1 failed at time 0`

My System:
Windows 10 64bit
Fusion 17.1.1. build 10
Cryptomatte 1.4.0

I use the sample image bunny_CryptoObject.exr

Could someone give me a hint?

Thank you,

**Comment by eoyilmaz** [comment]
Is there an update on this issue, I started to get this after upgrading to 1.4.0 from 1.2.6 (I believe)...

I'm under Fedora 36, both 17.3 and 18.0.b4 are giving the same error.

**Comment by eoyilmaz** [comment]
It seems that the issue is related to Reactor, so installing Cryptomatte through Reactor causes this error, following the native installation instructions solved this issue.

**Comment by schellicon** [comment]
i resettet my whole fusion, followed the instructions but same here.....

...te/Cryptomatte-1.4.0/fusion/Fuses/Matte/cryptomatte.fuse:259: attempt to call field 'log_info' (a nil value)
stack traceback:
	...te/Cryptomatte-1.4.0/fusion/Fuses/Matte/cryptomatte.fuse:259: in function <...te/Cryptomatte-1.4.0/fusion/Fuses/Matte/cryptomatte.fuse:251>
Cryptomatte1 failed at time 0

tested fusion 18 and 17 no success
reactor is uninstalled and all blackmagic directorys are renamed/removed

ok just realized... in resolve it`s working, fusion not

**Comment by SteffenDuenner** [comment]
Same here in Win10 Fusion Studio 9 and 18. Tried both Reactor and manual install.

Funny is it works like a charm in Linux Fusion 9

**Comment by tinogithub** [comment]
> Hello,
> 
> there is an error I get when piping an EXR into the Cryptomatte-Node.
> 
> `...s/Cryptomatte-master/fusion/Fuses/Matte/cryptomatte.fuse:259: attempt to call field 'log_info' (a nil value) stack traceback: ...s/Cryptomatte-master/fusion/Fuses/Matte/cryptomatte.fuse:259: in function <...s/Cryptomatte-master/fusion/Fuses/Matte/cryptomatte.fuse:251> Cryptomatte1 failed at time 0`
> 
> My System: Windows 10 64bit Fusion 17.1.1. build 10 Cryptomatte 1.4.0
> 
> I use the sample image bunny_CryptoObject.exr
> 
> Could someone give me a hint?
> 
> Thank you,

Hello, still getting the error now in Fusion 18.6.1 and older versions.
Tried Reactor and manually installation.

What is this error related to?

**Comment by eoyilmaz** [comment]
@tinogithub search for `cryptomatte_utilities.lua` file under the reactor folder, it might been left from your previous install. Also try adding the `Cryptomatte-master/fusion/Fuses/Matte/` to your `LuaModules` under `Preferences -> Path Map`... I'm under MacOS and everthing works fine with manual installation...

**Comment by tinogithub** [comment]
Thank you @eoyilmaz . I followed your help but no luck.

**Comment by eoyilmaz** [comment]
It seems that in your configuraion Fusion cannot find the `cryptomatte_utilities.lua`, you can copy/paste it to over other folders that you know you have some lua scripts that are running without any issues.

**Comment by tinogithub** [comment]
@eoyilmaz you saved my day. I have searched for this file on my system and found it again in Fusion\Modules\Lua.
So it was a conflict of different version of cryptomatte_utilities.lua files.
In the end I think that it must have been my fault because of various installation approaches. But I have always just looked at the cryptomatte.fuse file.

Thank you very much.
