### ISSUE TITLE
Cryptomatte Nuke not picking up Vray pass names

### ISSUE THREAD

**Issue by coderedfox** [Psyop/Cryptomatte#19]
Hello,

Having an issue getting renders to work from 3dsmax/Vray 3.60 to Nuke. VRay will auto name the pass "VRayCryptomatte" for example. Now I can see this channel in Nuke but the Cryptomatte gizmo will not pick it up (automatically I'm assuming?). Even if I type in the channel name into "Layer Selection" it still wont work.

If I use a provided sample image and connect the Cryptomatte the "uCryptoAsset" is seen. I can then name the vray pass "uCryptoAsset" and switch the input to this file and it works.

Is there something I'm missing coming from the VRay side? There is very little VRay documentation on this new feature. 

Thanks for your time.

**Comment by acjones** [comment]
This sounds like it could be an issue with exr metadata.  In order to work, the exr file needs to have channels that match the name of the Cryptomatte layer.  For example, in the metadata in Nuke you should see:

/exr/cryptomatte/<unique hash>/name = VRayCryptomatte

And the file should have layers like this:

VRayCryptomatte
VRayCryptomatte00
VRayCryptomatte01
VRayCryptomatte02

I don't currently have easy access to the latest VRay.  Any chance you could send an example file of what VRay is generating?

**Comment by coderedfox** [comment]
OK, So with that info I was able to determine VRay is NOT saving that metadata. In Nuke if I add the metadata (ModifyMetaData)
action: Set
key : exr/cryptomatte//name
value : VRayCryptomatte

The gizmo works as it should. So this must be a 3dsmax/VRay bug as its not adding that metadata. Or I'm just missing something.

Thanks

**Comment by acjones** [comment]
Yes, could be a VRay issue.  There's also a chance it could be a Nuke issue.  Don't quote me on this, but I've heard that the EXR 2.0 spec asks for metadata to be stored per-layer in multi-part EXRs, but that Nuke has trouble reading metadata in that case.  So it's possible that VRay is doing the right thing, and Nuke is just not handling it properly.

In theory, Cryptomatte can still be reasonably effective for matte extraction without metadata, but it's not a use case we've tested, and things like auto-setup and hash string recovery definitely won't work.

**Comment by coderedfox** [comment]
Here is how I got it working

![cryptomatte_example](https://user-images.githubusercontent.com/12239283/27660322-9ee83d86-5c0b-11e7-82d8-490087f86c29.jpg)

**Comment by vkoylazov** [comment]
V-Ray only writes the metadata in multichannel OpenEXR files straight from the renderer. If you saved the file from the VFB directly with the save button, it will not include the metadata right now. We need to expand the VFB to store and load the metadata, but it will be done in a future release.

Best regadrs,
Vlado

**Comment by Tylox81** [comment]
Hi Guys,

Any idea how CryptoMatte works with for example an object behind glass ? With Multimatte, it works when we check the affect all channels on the glass material, but it seems that the cryptoMatte doesn't work with this option. Any idea ?

**Comment by Tylox81** [comment]
Another problem for me, with vray 3.60 of course, when i put a CryptoMatte on render elements, 3dsmax crash everytime when he's writing output, and just the CryptoMatte element !!!

**Comment by vkoylazov** [comment]
If you have a scene that causes a crash feel free to attach it here or to email it to me. It generally works fine for me, but there might be things I've missed. Like I said, it only works with multichannel OpenEXR output. You can't use the option to split the render elements into separate OpenEXR files.

For objects in reflections and refractions, this is not supported right now. There is a thread on the Cryptomatte mailing list about this, and when things get clarified a bit more, I will look into implementing it.

Best regards,
Vlado

**Comment by Tylox81** [comment]
Ok , thanks Vlado, it works with the multichannel output. 
Last thing, when you have a multi/Sub Material, it doesn't understand, it just takes the global mat. Anyway to bypass ?

**Comment by vkoylazov** [comment]
That's the other thing that I haven't done yet. The current implementation can't see inside the Multi/Sub material, it just knows the top material that's assigned to the object. I will be reworking this part at some point to grab the actual material after it has been evaluated. I also have to figure out what to do with blend materials.

**Comment by Tylox81** [comment]
Great !!!! wait for the next vray update :)

**Comment by jonahfriedman** [comment]
Glad to see this getting resolved. FWIW Arnold Cryptomatte has the same limitations, images saved from the render views do not have the right data. 

Closing this because it's not an issue for the code in this repo. Thanks!
