### ISSUE TITLE
Plugin dosn't work with color picker

### ISSUE THREAD

**Issue by djdimidrol** [Psyop/Cryptomatte#20]
I've tried sample images and it looks like it works only with names in matte list. If click "picker add" it adds to matte list a color code but dosen't made any mattes. If I write "bunny" it works fine.
Nuke 9

**Comment by acjones** [comment]
It sounds like you're running into this issue:

(From troubleshooting.md)
> Keying just selects numbers such as <0.1234> but nothing lights up and no mattes are created.
> 
> Make sure your nuke viewer has "Use GPU for viewer when possible" set to off. Mouse over the viewer window and press S to get to your viewer options. If this is set to on, sometimes the values are changed by an infinitesmal amount and keying no longer works.

Can you try disabling "Use GPU for viewer when possible" and let us know if that fixes the issue?  Thanks!  If so, it might be worth filing a bug report with The Foundry for this, as it seems reasonable to expect the picker to return the exact value, regardless of the viewer acceleration.

**Comment by djdimidrol** [comment]
Hmm.. yes it works fine now) Thanx)

**Comment by acjones** [comment]
Good to hear.  We may consider adding some kind of UI warning to make this more obvious for users.
