### ISSUE TITLE
After Effects support

### ISSUE THREAD

**Issue by 23d1** [Psyop/Cryptomatte#21]
Any plans for an After Effects plugin (or knowledge thereof), would it even be possible? The reason I ask is because it's my go-to for simple compositing and 2.5D animation. Mostly since Nuke is so expensive.

Photoshop support would be rad too for still work, but I'm probably already pushing it with AE. ;)

**Comment by jonahfriedman** [comment]
No current plans to develop that on our part. However this is an open source project and if someone steps up, that'd be fantastic. 

If this is something you want, (especially if you'd be willing to pay for it), I would suggest contacting developers of AE and PS plugins and ask for it.
