### ISSUE TITLE
Which characters are not allowed in object/materials/etc names?

### ISSUE THREAD

**Issue by vkoylazov** [Psyop/Cryptomatte#22]
So that's is another issue that came up in 3ds Max besides Unicode characters. In 3ds Max, object and material names can contain absolutely any characters - including spaces, commas, slashes, quotes etc. However if an object name includes f.e. spaces, it is no longer selectable by the Nuke Cryptomatte plugin.

The Cryptomatte specification does not say anything about these characters. Should they be replaced by some other valid character, f.e. underscores? Or should the Cryptomatte plugin for Nuke be updated to handle such object names properly? How should quotes be treated (i.e. should they be escaped with a back slash)?

Best regards,
Vlado

**Comment by jonahfriedman** [comment]
Hi Vlado,

I think all characters should be allowed that can be encoded into the json manifest. However you're right that the Nuke implementation does not currently support this. 

Right now, if you're using the sidecar_manifests dev branch, here's what's not supported:

* Names that start or end with white space
** In the release branches, any white space does not work
* Names that start with "<" or end with ">". 
* Names containing commas (","). 

This is a limitation of the plugins that we should look at fixing. There's no fundamental reason why these cases should not be supported. Thanks for the report.

**Comment by jonahfriedman** [comment]
I've made a change that should allow anything you can put into a valid JSON with the exception of strings that both start and end with <>. We'll consider whether this limitation should be an implementation detail of the decoder or something to go into the spec, but for now it's an implementation detail. 

The plugin uses YAML internally to encode and decode the matte list. The reason for this is yaml lists look basically like what we've been doing- a comma separated list of strings without quotes becomes a list of strings, but it can also handle all the more difficult cases as well. For example: [hello, <1.3>, "string with spaces, and commas"]. The Nuke plugin removes the "[]" characters in the list shown users. (This is just an implementation detail of the Nuke plugins).
