### ISSUE TITLE
Metadata documentation is erroneous

### ISSUE THREAD

**Issue by lightwolf** [Psyop/Cryptomatte#24]
The specification PDF describes the labels of the metadata to be of the type:

**exr/cryptomatte/#hash#/***

This is not how the metadata should be stored in the OpenEXR file itself, that should be:

**cryptomatte/#hash#/***

**exr/** seems is a prefix attached automatically by Nuke to designate the source of the metadata.

**Comment by jonahfriedman** [comment]
Ah, thank you, we'll clarify that.

**Comment by jonahfriedman** [comment]
This is done and will be in the next release. Thanks!
