### ISSUE TITLE
Problem with the Fusion version

### ISSUE THREAD

**Issue by ignaciox10s** [Psyop/Cryptomatte#26]
Hi there, I don't know if this is the right place to write this, but...

Well we installed the version of Fusion in several computers and we can't see anything when we select the node.  actually is missing the arrows that we can see on the reference videos you uploaded.
we copied the Fuse in the Fuse folder, and the other files in the root of Fusion. ( 7 and 8 studio )

Could be soo cool having this working, is something you knew already?thanks!

**Comment by Gil-1** [comment]
Hello,

I have the same issue (I think) with Fusion 9. Here is the console output :
 
... Files\Blackmagic Design\Fusion 9\Fuses\cryptomatte.fuse:684: attempt to index a nil value
stack traceback:
	... Files\Blackmagic Design\Fusion 9\Fuses\cryptomatte.fuse:684: in function 'extract_cryptomatte_metadata'
	... Files\Blackmagic Design\Fusion 9\Fuses\cryptomatte.fuse:780: in function <... Files\Blackmagic Design\Fusion 9\Fuses\cryptomatte.fuse:775>
Cryptomatte1 failed at time 0

**Comment by jonahfriedman** [comment]
Hi ignaciox10s and gil-1, 

Sorry for the trouble. Can either you supply an EXR file showing these issues?

**Comment by Gil-1** [comment]
Hello,

For my part I wasn't exporting the image the right way with Vray 3.6.03.
The Cryptomatte wasn't stored correctly.

The correct way is to render with the Vray Frame Buffer and store the image with V-Ray raw image file option in the Frame Buffer Settings.

**Comment by jonahfriedman** [comment]
Thanks @Gil-1 gil-1,

@ignaciox10s, was that your issue too?

**Comment by ignaciox10s** [comment]
sorry Im on vacation now i can't send anything until friday, but i tried
with the EXR that you provide too, looks like a fusion node problem because
appears without the input arrows. maybe i didnt install something properly.

thanks

**Comment by jonahfriedman** [comment]
No problem. I'm going to close this for now, assuming incorrect installation, but if you come back from vacation and that doesn't seem to be the case (for example- the example images work, but your image doesn't), then please don't hesitate to reopen this. 

If that is the case, console output like @Gil-1 provided will be useful in diagnosing the problem.
