### ISSUE TITLE
How can i use it on Katana

### ISSUE THREAD

**Issue by jiexiajoy** [Psyop/Cryptomatte#28]
How can i use it on Katana?
Katana Arnold export one channel  cryto_object and do not have cryto_object00 cryto_object01 cryto_object02?
How can i export on katana?

**Comment by jonahfriedman** [comment]
It only writes those extra channels and metadata when writing an EXR to disk. You probably can't save it properly using the UI, only EXR renders straight to disk will work. 

This is assuming everything else is working, of course. There's been recent talk about making it work better in Katana, but that's more about how the mattes are organized than getting it working in the first place, but in any case stay tuned. 

By the way, for future reference this is not exactly the right place for this ticket  (the Arnold implementation doesn't live in this repo, perhaps the KtoA list or AlShaders2 repo is the best place), but it's no problem.
