### ISSUE TITLE
Layer Selection, Cryptomatte Node - Fusion

### ISSUE THREAD

**Issue by danyrene** [Psyop/Cryptomatte#29]
Hi there,
I am writting this message because I have an issue and to be honest I do not know how to solve it. I created a .exr file using Vray, that file constains three differents cryptomattes. So I import it in fusion 8 and when I try to change the layer selection in cryptomatte node, nothing happen. It is like this option is blocked because I cannot type anything on it. thank you

**Comment by jonahfriedman** [comment]
Hi danyrene, 

Can you supply an EXR file containing the cryptomattes? It may help diagnose the issue. 

If you can't give us production files, could you just create a scene with a few spheres in it and the same cryptomattes, and do a low resolution render?

**Comment by danyrene** [comment]
Hi JonahFriedman,

Thank you for your reply. I have attached the .exr file here, it constains three cryptomatte Layers and the names are: 

VRayCryptomatte_Hierarchy
VRayCryptomatte_ID
VRayCryptomatte_Mtl

As I mentioned before I can not change the layer selection in cryptomatte node, thank you.

[Test1.zip](https://github.com/Psyop/Cryptomatte/files/1226639/Test1.zip)

**Comment by jonahfriedman** [comment]
@danyrene 

There's nothing wrong with this Cryptomatte, and it works perfectly fine in Nuke. You are correct that the Fusion plugin can't currently set the selection.

We'll fix this, but as a temporary workaround, you can render each of your Cryptomattes in separate EXR files.

**Comment by cedricduriau** [comment]
Hi @danyrene 

Currently the layer selected is just a display of the top layer, actual control over layer selection is not supported yet, but this is the main focus right now. Expect an implementation soon.

Cheers
Cedric

**Comment by danyrene** [comment]
Hi jonah friedman and cedric duriau,

Thank you for your comments about it. At the moment, I will work with separate Cryptomattes, as jonahfriedman recommended me and I will check the web oftenly to know any new fusion version.

Thank you for your help,

Cheers
Dany

**Comment by jonahfriedman** [comment]
This has been fixed and will be in the next release (probably later today)! FYI however, it does require Fusion 9.0.1.
