### ISSUE TITLE
Version numbers and releases

### ISSUE THREAD

**Issue by shidarin** [Psyop/Cryptomatte#3]
Any chance of adopting a release workflow with version numbers? This helps with determining what version of software we have installed and comparing it the repository, especially since installations usually no longer have the git repository with them.

**Comment by jonahfriedman** [comment]
Good point, will look at the best way of doing that.

**Comment by jonahfriedman** [comment]
With version 1.0.1, we've gone to doing tags as well as adding the version number as the `__version__` in cryptomatte_utilities.py. Thanks!
