### ISSUE TITLE
bunny test image missing color

### ISSUE THREAD

**Issue by dekekincaid** [Psyop/Cryptomatte#33]
Would it be possible to get cryptomatte example images which has the color in the rgba of the bunny?  Not just the cryptomatte channels?

**Comment by acjones** [comment]
Hey Deke,

Yeah, I think this will be forthcoming relatively soon.  The upcoming beta has some changes to make the multichannel experience better, including the ability to direct mattes into an arbitrary mask channel, and to view the rgba (or even other nodes) when picking mattes.  So, it will make sense to have a sample image that lets users test those features.

**Comment by dekekincaid** [comment]
Ok, I'm just trying to use vray's new cryptomatte support but it is not working so I wanted to have an image to compare to where the tool does work in Nuke.

**Comment by jonahfriedman** [comment]
Ah, issue #29 has some vray images attached that are working fine, which you could test.

**Comment by jonahfriedman** [comment]
Cleaning out some old tickets. I think we won't do this, unfortunately. (I don't actually have the matching renders and the tests rely on the example images being the way they are.)
