### ISSUE TITLE
No Matte Visible in Nuke

### ISSUE THREAD

**Issue by CutterSnake** [Psyop/Cryptomatte#34]
Hey,

i do have this strange issue where i do not know where this comes from. 

I am using Maya / VRay 3.6 / Nuke 10.5 and 11 

![cryptomatte](https://user-images.githubusercontent.com/31931998/30388870-702f47a4-98b1-11e7-9307-e18b233fe11a.JPG)

**Comment by jonahfriedman** [comment]
I don't understand your issue. Could you describe it?

**Comment by CutterSnake** [comment]
I just got it.

The Issue was that when you render the Image with the VRay VFB and saved it as an exr from there, the Cryptomatte does not seem to work propper. It showd the image you see there on my left viewer. Even if there is a Matte Pass in it (used a shuffle to make it visible that there is realy a matt pass in there)

Solution for me was simple - i just need to render the image via the batch render and not with the VFB.

**Comment by jonahfriedman** [comment]
Ah, thanks.
