### ISSUE TITLE
"do not attach prefix" in Nuke breaks gizmo

### ISSUE THREAD

**Issue by dekekincaid** [Psyop/Cryptomatte#36]
Hi Folks

Nuke does this silly thing where it appends the file format to all the metadata keys.  
IE 
cryptomatte/881c23b/manifest
becomes
exr/cryptomatte/881c23b/manifest

On both read and write nodes we turn on the knob "do not attach prefix" to get rid of this silly addition as Nuke is kind of dumb as next time you write out a file with metadata the existing metadata will become exr/exr/cryptomatte and if you write it again it will become exr/exr/exr/cryptomatte.

The trouble is the gizmo breaks when you turn  "do not attach prefix".  You guys should make it work with and without this on.

**Comment by jonahfriedman** [comment]
Good observation, thank you for the report. This should be pretty simple to get fixed.

**Comment by jonahfriedman** [comment]
This is fixed in the latest dev branch, which should be released later today. Thanks!
