### ISSUE TITLE
Cryptomatte pickerAdd,pickerRemove knob issue

### ISSUE THREAD

**Issue by kerekb** [Psyop/Cryptomatte#38]
Hey there! 

We updated to the latest Cryptomatte and on Windows i see no problem, but linux renders give an error. We found out, that using the pickers will add an array as the knob value. 

 pickerAdd {0.09262084961 0.2319335938 0.177734375 0 372 482 373 483}

If we override this before the actual render to 0, everything works OK. 

Not sure if anybody else encountered this issue, but I had to zero these values out for every single cryptomatte node in the scene to be able to render it without freeze on Linux. On Windows this works.

**Comment by jonahfriedman** [comment]
Hi @kerekb,

Thanks for reporting. Could you give a little more information? What version of Nuke, and what is the error?

**Comment by jonahfriedman** [comment]
Also, if you would like it'd help me if you could try an experiment. 

In the gizmo, could you add +DO_NOT_WRITE to the lines that create those knobs, and see if that fixes the issue? (Or at least keeps the issue from affecting newly created gizmos).

**Comment by kerekb** [comment]
Adding +DO_NOT_WRITE to the end of the addUserKnob at line 11,15 for the Gizmo fixes this issue! Thanks!

**Comment by jonahfriedman** [comment]
Thanks, that helps a lot. I'll leave this ticket open until we incorporate that in the next version (if everything goes well). 

In the meantime, if you could help by keep a lookout for this issue coming back, to confirm that this really does fix it, I'd appreciate it.

**Comment by jonahfriedman** [comment]
The change we talked about will be in the next version.
