### ISSUE TITLE
Transparency and Cryptomatte

### ISSUE THREAD

**Issue by Benoeat** [Psyop/Cryptomatte#53]
Hi

In 3dsmax/Vray is there a way to have the all channels refract option in the cryptomatte ?

I mean when i make a matte of a window glass i want to have the object behind it

Thanks

**Comment by jonahfriedman** [comment]
Hi @Benoeat,

This isn't exactly the right place for this, this repo is for the Nuke plugin and the standard, so I would direct any questions about the VRay implementation to Chaos Group. However, VRay 3.60.03 (at least for Maya) does indeed support Cryptomatte through refraction. I'm not sure about about the 3DSMax plugin. 

https://forums.chaosgroup.com/forum/v-ray-for-maya-forums/v-ray-for-maya-announcements/976836-v-ray-3-60-03-for-maya-now-available
