### ISSUE TITLE
Cryptomatte With Tiles 

### ISSUE THREAD

**Issue by cjagman123** [Psyop/Cryptomatte#54]
Hey Guys 

I hope all is well you are having a great holiday. I have come across and issue when using cryptomatte, we deal with really large images for print and in order to get renders turned around we do a lot of tiles. I have noticed when we do the tiles and combine them all together in nuke we can use the cryptomatte gizmo without a problem, however, when we try to merge the metadata streams from all the exrs to create a flattened exr and that exr is read back in the gizmo no longer works. I suspect that when the tiles are merged and the gizmo is placed inline after the merge the original metadata streams can be parsed independently, but when we merge the metadata and make a single image somehow they do not play well together. 

Has anyone else come across this?

Should i be looking to combine these images with something OpenExr Commandline?

**Comment by sjacobrodeofx** [comment]
*when we try to merge the metadata streams from all the exrs to create a
flattened exr and that exr is read back in the gizmo no longer works.*

Rings a bell

Are the resulting crypto aovs's in the flattened exr 32bit? If the metadata
and pixels are there, sounds like a bitdepth issue.

For mixed bit depth files, multipart exr's are the answer.

**Comment by cjagman123** [comment]
That's a good point I have not checked the bitdepth that we are outputting. We are using the standard vray crypto and using the stock output at 16bit. I will try running with the 32 bit and multipart exr options. Thanks for the quick response. I will let you know what I find.

**Comment by jonahfriedman** [comment]
Also, see this ticket: https://github.com/Psyop/Cryptomatte/issues/36

(The issue in that ticket was fixed but extra metadata keys may be tripping you up)

**Comment by jonahfriedman** [comment]
@cjagman123 Did this work, can we close this? 

Cryptomattes must be 32 bit, the ones written out of VRay are no exception.

**Comment by cjagman123** [comment]
Thanks Jonah

We did not realize that the exr was a multipart exr. I wrote out the tiles at a 32-bit exr and everything works as expected. Thank you.

**Comment by jonahfriedman** [comment]
Thanks, @cjagman123
