### ISSUE TITLE
Disabled Cryptomatte gizmo raises exceptions in non-GUI mode

### ISSUE THREAD

**Issue by nrusch** [Psyop/Cryptomatte#6]
If you start Nuke in terminal mode and open a script that contains a disabled Cryptomatte gizmo, the `knobChanged` callback will raise one or more exceptions during the script loading process, depending on the state of the saved gizmo. I've looked over the code, and basically the issue is that in this particular scenario, the node metadata lookup will return None.

https://github.com/Psyop/Cryptomatte/blob/master/nuke/cryptomatte_utilities.py#L86

I don't really have the time to sort this out and submit a pull request right now, but the fix is very simple: Check if `exr_metadata_dict is None` and bail out if it is.

**Comment by jonahfriedman** [comment]
Ah, we fixed this once before, it's a regression. The issue was as you say. We'll get it fixed after SIGGRAPH. 

Thanks a lot for reporting.

**Comment by jonahfriedman** [comment]
This is fixed in the dev branch, it'll be in the next release. Thanks again.
