### ISSUE TITLE
Node name with hierarchy ?

### ISSUE THREAD

**Issue by Benoeat** [Psyop/Cryptomatte#60]
I don't understand the way "Node name with hierarchy" work.

i thought that it render me object by link or group but in fact it render me the same that the "Node name"
just in different color but not the grouped or linked objects.

i render in Vray/3dsmax and compositing in Nuke

**Comment by vkoylazov** [comment]
The only difference is in the manifest - the full object paths are exported and not just the object names. The expectation is that you could use wildcards to select parts of the hierarchy, if and when such a capability is added to the Cryptomatte plugins.

**Comment by jonahfriedman** [comment]
Thanks Vlado.
