### ISSUE TITLE
postage stamp icon in Nuke

### ISSUE THREAD

**Issue by sharktacos** [Psyop/Cryptomatte#63]
I'm noticing that in Nuke the Cryptomatte icon will sometimes show a little "postage stamp" image of the matte, but usually the icon is just black. I'm not sure how to get it to show the matte in the postage stamp consistently or correctly (when it does show an image of the matte in the icon, it will not update the image when the matte is changed). 

It's possible this is just user-error on my part, and so if there is a way to get this working, I'm all ears! Thanks :)

**Comment by dgirondi** [comment]
Do you mean the node's postage stamp?

If so Nuke will always generate the postage stamp from the node's RGB output, so unless you output the matte to the "rgb/rgba" channels either by setting the matte output to the rgb/rgba layer or check the "Matte Only" option from Cryptomatte it will merely generate the postage stamp from the "rgb" that is passing trough the node.

As for the postage stamp not updating for the gizmo, that is also a Nuke thing. Postage Stamps in Gizmos don't quite follow how they work for compiled nodes. If you need "live" postage stamps your best option would be to add a PostageStamp node right after the Cryptomatte node. 

I'm afraid there isn't anything the Cryptomatte devs can do about this unless the move that node from a Gizmo over to a compiled node or Foundry changes the way this works for gizmos/groups.

**Comment by sharktacos** [comment]
Thank you Diogo, that's very helpful.

**Comment by jonahfriedman** [comment]
Diogo is correct and it's not something we can control  (as far as I know at least). Thanks!
