### ISSUE TITLE
Cryptomatte Nuke not picking up Arnold (5 for Maya 2018) pass names

### ISSUE THREAD

**Issue by tomVujnovic** [Psyop/Cryptomatte#65]
I'm reopeninig this (https://github.com/Psyop/Cryptomatte/issues/19) issue because there is a problem with metadata on output shaders from arnold.
Arnold implementation IS writing out metadata but in slightly wrong format.
Problem is in key name:
exr/cryptomatte/bda530a/....... (key that is present in exr file)
cryptomate for nuke expect that "cryptomate" keyword is folowed by number in base10 or nothing.

After some experimentation i found out that it works if I replace all "exr/cryptomatte/bda530a/" parts with "exr/cryptomatte/0/" or "exr/cryptomatte//" with ModifyMetaData node.
I don't know if that is Cryptomate for Arnold, or Arnold, or Maya bug, but it is an issue.

Tom Vujnovic

![screenshot 2018-02-05 23 15 09](https://user-images.githubusercontent.com/36174440/35831682-e621f73c-0aca-11e8-8d03-0a09f6ae97e5.png)

**Comment by jonahfriedman** [comment]
Luckily this is an easy one, I think you are using a very old version of Cryptomatte. I had to go back and look - we made this change to the specification and released Nuke plugins updated to use it in October 2016. 

Issue #19 was different, it had to do with having no metadata at all due to writing out images from a render view instead of a batch render, so a bit different. 

The metadata IDs can now be any string, and are recommended to be hex hashes, and the Arnold implementation is doing the right thing.

**Comment by tomVujnovic** [comment]
But I downloaded it from https://github.com/Psyop/Cryptomatte less than an hour ago ???
.t.

**Comment by jonahfriedman** [comment]
Maybe double check you don't have it installed in two places? It looks like it's reading the python files from: c:/users/administrator/.nuke

That code that it's referencing in the console window has not existed for a long time.

**Comment by tomVujnovic** [comment]
that's where I installed as instructed in zip file that I downloaded from link I posted i previous mail :(

.t.

**Comment by jonahfriedman** [comment]
Which version did you download? Also, did you make sure to overwrite c:/users/administrator/.nuke/cryptomatte_utilities.py?

At the top of that file, it may say what version it is like [so](https://github.com/Psyop/Cryptomatte/blob/master/nuke/cryptomatte_utilities.py#L8), unless it's so old that it's before we started doing that. 

Here's what line [90 looks like now](https://github.com/Psyop/Cryptomatte/blob/master/nuke/cryptomatte_utilities.py#L90) in cryptomatte_utilities.py, so the file that Nuke is loading is very old.

**Comment by tomVujnovic** [comment]
Now I checked and in my download it is old version, on github it's newer one. I don't know how I succeded in downloading old version ???
I'll try again.
thnx.
.t.

**Comment by tomVujnovic** [comment]
Works like a charm now.
Thanks a lot.
I really don't know how I downloaded old version. :))))

.t.

**Comment by jonahfriedman** [comment]
No problem! 

Just a wild guess, maybe you scrolled down in releases and downloaded the oldest one when you intended to download the newest.
