### ISSUE TITLE
Maya/Renderman userAttribute

### ISSUE THREAD

**Issue by Kikefluk** [Psyop/Cryptomatte#69]
Hello,

Could you give me the name and where I should put the "string user attribute" to have the cryptomatte work with that specific layer mode? Should I create a specific renderman attribute on the shape? group? material?

Thanks and fgreat job by the way!
Kikefluk

**Comment by jonahfriedman** [comment]
Hi @Kikefluk,

I'm not a RenderMan developer so I don't know, for a definitive answer I would ask Pixar's RenderMan support. I would guess it's on the shape, but a quick glance at the docs did not immediately reveal how to add user attributes in Maya that will end up in the renderer.

Thanks!
Jonah
