### ISSUE TITLE
renderman  sequence for Cryptomatte

### ISSUE THREAD

**Issue by parin2424** [Psyop/Cryptomatte#70]
How to render sequence of Cryptomatte?

**Comment by jonahfriedman** [comment]
For RenderMan questions, I would contact their support team or use thier forums.

However, it just so happens this was already [answered on their forums](https://renderman.pixar.com/forum/showthread.php?s=&threadid=36985), by user earlywill: 

> 
> Try cryptomatte.${F4}.exr
> 
> That should do the frame number with four-frame padding.
> 
> Cheers,
> Will
