### ISSUE TITLE
Fusion 9.02 Rendernode implementation

### ISSUE THREAD

**Issue by unexpectedphlip** [Psyop/Cryptomatte#71]
Hi Guys,

i'm trying to implement cryptomatte on our rendernode installations.
But i'm not able to get it working, as the installation instruction does not fit the circumstances of a rendernode installation.

I guess the issue itself is related to the LUA_PATH variable or package.path which seems to be ignored by Fusion. As the Rendernode shows an error which says cryptomatte_utilities.lua not found.

This even appears when i tried to:
set the LUA_PATH Windows environmental variable
Set package.path fusion variable

Copied all the files as described in the readme, but replaced the folder paths:
"C:\Program Files\Blackmagic Design\Fusion 9\"
with
"C:\Program Files\Blackmagic Design\Fusion Render Node 9\"
I had to create the subfolders for "config" and "lua" as they didn't exist.

I tried the workaround where you have to copy the cryptomatte_utilites.lua to "C:\......\AppData\Roaming\Blackmagic Design\Fusion\Modules\Lua".

Your script could safe us a lot of work if we would be able to use it on our renderfarm :)

Best regards,
Philipp

**Comment by AndrewHazelden** [comment]
Hi @unexpectedphlip.

You might consider this Cryptomatte installation solution listed on the Fusion user community site steakunderwater: 

https://www.steakunderwater.com/wesuckless/viewtopic.php?p=14513#p14513

**Comment by unexpectedphlip** [comment]
Hi Andrew,

Thanks for your fast response.
i've installed reactor on one of our workstations then i've set the REACTOR_INSTALL_PATHMAP and set it to a path on a networkdrive.
Then i've moved the folder C:\programData\Blackmagic Design\Fusion\Reactor\ to the desired location.

Installed cryptomatte, but there were no files created on our networkpath, i'm not able to find the cryptomatte.fuse or cryptomatte_utilities.lua in any location.

C:\Program Files\Blackmagic Design\Fusion 9\Fuses
C:\ProgramData\Blackmagic Design\Fusion\Fuses
C:\Users\Stefan.Bucher\AppData\Roaming\Blackmagic Design\Fusion\Fuses
Z:\UTILITY\TOOLS\Reactor\Deploy\Fuses

But it seems to be existing somewhere on the workstation as i'm able to create a cryptomatte object? 

Regards,
Philipp

**Comment by AndrewHazelden** [comment]
To search for all of the installed Fuses on a Fusion system you can use a Reactor package called “Fuse Scanner”.

It is found in the “Scripts/Reactor” category.

If you want to see the environment paths that are active in Fusion on your system you can use this tool:

https://www.steakunderwater.com/wesuckless/viewtopic.php?t=1411

**Comment by jonahfriedman** [comment]
Thanks everyone, I've labeled this as a question, and I think it's been answered, so I'm going to close it. Feel free to keep adding more information if there's something that should be here.
