### ISSUE TITLE
encryptomatte examples for nuke?

### ISSUE THREAD

**Issue by dekekincaid** [Psyop/Cryptomatte#73]
Are there any example scripts of using encryptomatte in nuke?  I'm trying to use it for roto with a few different shapes, and different variations of the same shapes (motionblur 90/180 shutter) and put those on different layers, ie base/motionblur 90/motionblur 180.  It doesn't seem to work for me so I was hoping either 1. i am using it wrong or 2. something in my workflow is breaking with encryptomatte.  Hopefully it is just 1.

**Comment by jonahfriedman** [comment]
Hi Deke,

Unfortunately we don't, but I think we can make this a ticket to add one. The issues I've seen people have are usually getting things to update properly. 

I just tried to create a step by step for setting up a new Cryptomatte, and found something that could easily trip people up. 

1. Create a roto shape.
2. Create a constant node*
3. Select the constant node and create an encryptomatte node. Set layer selection to "cryptoRoto" (or whatever) and enable "setup layers". 
3. Plug the roto into encryptomatte.matte
4. Create a cryptomatte node to see the results. 

* I think the fact that this step is necessary should be considered a bug.

**Comment by jonahfriedman** [comment]
I have fixed the issue with setting up Encryptomatte without any inputs, and it should be in the next release. (dev branch).
