### ISSUE TITLE
Fusion cryptomatte newbie question

### ISSUE THREAD

**Issue by MarkusSchille** [Psyop/Cryptomatte#74]
Hi. I've rendered a sequence in Vray where I created a cryptomatte renderpass, just to test if I could use it. I'm using After Effects for compositing, so I render each pass to a separate exr sequence since my experience is that it's faster in AE when not using layered exr's.

AE does'nt have cryptomatte support yet AFAIK, but I've tested the cryptomatte plugin and demo files in Fusion 9.02. (the free version), The demo file works, but my renders doesn't. 

I think the plugin expects a layered exr file, but mine are in separate files for each layer. Does anyone have any ideas on how I can combine them (without re-rendering in v-ray), or make them work with Fusions cryptomatte node? I'm a complete newbie in Fusion btw.

**Comment by vkoylazov** [comment]
I'm not sure if it's similar in AE, but in Nuke working with multi-part layered OpenEXR files is a lot faster compared to just plain (non-multipart) OpenEXRs. Maybe it could be worth exploring this option. The multi-part option is available as part of VRayOptionRE in 3ds Max, and as part of the Image Format Options dialog in Maya.

**Comment by MarkusSchille** [comment]
It's been a while since I've tested using multilayered exr's in After Effects, but other ae users are complaining that it is very slow when using multilayered exr's (so the opposite of Nuke). I might give it a go anyways, just to check if there is any improvement, but is there a way to build a new multilayered exr from a bunch of files. What software can do this?

**Comment by jonahfriedman** [comment]
Also FYI, there is a beta starting of Cryptomatte in AE: 

Mac: http://www.fnordware.com/ProEXR/ProEXR_v2.0b3_mac.dmg
Win: http://www.fnordware.com/ProEXR/ProEXR_v2.0b3_win.zip

By Brendan Bolles, as part of the ProEXR plugins. 

As for having all the layers of Cryptomatte in separate files, they have to be in multilayer EXRs. In the original implementation, if you aren't rendering each AOV to its own file, it treats the whole Cryptomatte as one file.

**Comment by MarkusSchille** [comment]
Thanks for the tip. I saw fnordware post in this thread https://forums.adobe.com/thread/2356713 that they might make an AE plugin for Cryptomatte, but I didn't know it already was in beta. I can't find any more info about it on the fnord website.

**Comment by jonahfriedman** [comment]
It's brand new, and I contributed a little bit to it myself. Give it a shot, and post feedback on the fnordware github.

**Comment by cedricduriau** [comment]
Hi @MarkusSchille 

I'm curious on why your single layer EXR files didn't work in Fusion.
Could you provide them or test images for me to have a look?

Cheers
Cedric

**Comment by junglejuz** [comment]
I'm not able to get it working using single layer EXR files either. V-ray outputs 4 separate cryptomatte EXR files, and none of them work using the Crytpomatte node in Fusion.
Any ideas?

**Comment by vkoylazov** [comment]
Cryptomatte's are generally only meant to work with multi-channel OpenEXR files. I know that in Nuke you can reassemble several single channel files so that the Cryptomatte plugin for Nuke recognizes them, but I'm not sure how to do this in Fusion or AfterEffects.

**Comment by junglejuz** [comment]
I was reading somewhere that you can combine EXRs in Fusion to a multichannel EXR using the auxiliary channels in the Channel Boolean node, but this is beyond my knowledge and the post was over 10 years old.
