### ISSUE TITLE
Transparency Cryptomatte Vray for 3dsmax

### ISSUE THREAD

**Issue by Tylox81** [Psyop/Cryptomatte#75]
Hi guys,

i'm working on 3dsmax and vray and i can't figure it out how to enable transparency in cryptomatte. For example, i create a box with glass material, create some teapots behind with vray materials, and render it, the crypto doesn't see what's behind the glass !!! Some one has an idea ? 

Regards.

**Comment by jonahfriedman** [comment]
I would ask Chaos Group support for more accurate answers, but according to the [docs](https://docs.chaosgroup.com/display/VRAY3MAX/Cryptomatte+%7C+VRayCryptomatte), VRay cannot be propagated through reflections or refractions.

**Comment by vkoylazov** [comment]
You need to go to your glass material, and in the refraction section, set the parameter "Affect channels" to "All channels". This will propagate the Cryptomatte through the refractive material.

**Comment by Tylox81** [comment]
no sorry but this trick doesn't work for me... already tried of course....

**Comment by vkoylazov** [comment]
Ok, you can email me and I'll try to figure out what's going on.

**Comment by Tylox81** [comment]
hummm email you... when i find your email ?

**Comment by vkoylazov** [comment]
You can see it f.e. in this post:
https://forums.chaosgroup.com/forum/v-ray-next-beta-for-3ds-max/v-ray-next-beta-for-3ds-max-general/990696-vray-next-has-different-result-in-glassy-liquid-situations-than-3-60-even-in-phoenixfd-bubbles?p=991927#post991927

Best regards,
Vlado
