### ISSUE TITLE
Fusion 9.0.2 selection drops.

### ISSUE THREAD

**Issue by Resorsky** [Psyop/Cryptomatte#77]
Until the problem of droping matte is resolved plugin is useless, sory guys. Nothing helps, scripts, export only matte, anyway if i want export matte and use as mask i will be do it in maya. I could pay for this plugin even 100 bugs only if it work.

**Comment by acjones** [comment]
Hi Resorsky,

Apologies for the ongoing trouble.  Frustrations noted, but I'm closing this as a duplicate of https://github.com/Psyop/Cryptomatte/issues/46
