### ISSUE TITLE
issue with cryptomatte

### ISSUE THREAD

**Issue by pincixxxxx** [Psyop/Cryptomatte#78]
hi, when i load cryptomatte inside nuke i don't see the color selection, and in the node i  don't see a layer selection, so i think the cryptomatte don't read  the  object,asset, material and cryptomatte.

**Comment by dgirondi** [comment]
You don't see the knobs or they are merely empty?

If they are there but empty I would make sure the cryptomatte metadata and
data layers are indeed present on the stream.


cheers,
Diogo

**Comment by pincixxxxx** [comment]
i solve it :) the issue  is that i render the exr in progressive and not in bucket. thanks

**Comment by jonahfriedman** [comment]
@dgirondi Thanks for jumping in. 

@pincixxxxx - It's also good to mention what renderer you're using as well, since Cryptomatte is in several. Anyway, glad it's resolved.
