### ISSUE TITLE
Cryptomatte v1.2.2 does not start on macOS Fusion 9.0.2

### ISSUE THREAD

**Issue by movalex** [Psyop/Cryptomatte#84]
Cryptomatte fuse falls back with the error on Fusion launch.
Changing line 13 of the fuse to
`local cryptoutils = self and require("cryptomatte_utilities") or nil`
seems to fix the issue. 
Should I make a PR or it is known?

![](https://cl.ly/2o20141y2n2B/Screenshot%202018-08-10%2010.39.32.png)

**Comment by cedricduriau** [comment]
Hi @movalex 

The location of where to put the `cryptomatte_utilities.lua` is mentioned in the documentation, and shown as well in error message you provide. So to fix the problem, relocate the module to the specified location (`/usr/local/share/lua/5.1/`). 

I'll see to add the auto fallback to self line you provide in the future, but I need to double check the actual implications of that line.

Does this work for you in the meantime?

Cheers
Cedric

**Comment by movalex** [comment]
Hi!
Yes, adding this line works for me both on mac and windows if the module is installed into usual`..Blackmagic Design/Fusion/Modules/Lua` folder. 
BTW, these `/Users/macbuild...` file paths on the screenshot are nonexistent on my machine. And I have neither local Lua 5.1 installation nor `/usr/local/share/lua/5.1` folder or $LUA_PATH environment variable. So creating the folder and moving the module there does not fix the issue, because this folder also does not exist in `package.path` of the Fusion and causes a console error:

```
...rt/Blackmagic Design/Fusion/Fuses/Matte/cryptomatte.fuse:15: module 'cryptomatte_utilities' not found:
	no field package.preload['cryptomatte_utilities']
	no file '/Users/videopro/Library/Application Support/Blackmagic Design/Fusion/Modules/Lua/cryptomatte_utilities.lua'
	no file '/Library/Application Support/Blackmagic Design/Fusion/Modules/Lua/cryptomatte_utilities.lua'
	no file '/Applications/Blackmagic Fusion 9/Fusion.app/Contents/MacOS/Modules/Lua/cryptomatte_utilities.lua'
	no file '/Library/Application Support/Blackmagic Design/Fusion/Reactor/Deploy/Modules/Lua/cryptomatte_utilities.lua'
	no file '/Users/videopro/Library/Application Support/Blackmagic Design/Fusion/Modules/Lua/cryptomatte_utilities/init.lua'
	no file '/Library/Application Support/Blackmagic Design/Fusion/Modules/Lua/cryptomatte_utilities/init.lua'
	no file '/Applications/Blackmagic Fusion 9/Fusion.app/Contents/MacOS/Modules/Lua/cryptomatte_utilities/init.lua'
	no file '/Library/Application Support/Blackmagic Design/Fusion/Reactor/Deploy/Modules/Lua/cryptomatte_utilities/init.lua'
	no file '/Users/videopro/Library/Application Support/Blackmagic Design/Fusion/Modules/ll/cryptomatte_utilities.lua'
	no file '/Users/videopro/Library/Application Support/Blackmagic Design/Fusion/Modules/Lua/cryptomatte_utilities.so'
	no file '/Library/Application Support/Blackmagic Design/Fusion/Modules/Lua/cryptomatte_utilities.so'
	no file '/Applications/Blackmagic Fusion 9/Fusion.app/Contents/MacOS/Modules/Lua/cryptomatte_utilities.so'
	no file '/Library/Application Support/Blackmagic Design/Fusion/Reactor/Deploy/Modules/Lua/cryptomatte_utilities.so'
```

I also found out that some Fusion installations have empty or incomplete `package.path` contents, which also causes cryptomatte not to load. Adding correct path to the `cryptomatte.fuse` file before module initialization fixes that issue.

`package.path = package.path .. ";C:\\Users\\USER\\AppData\\Roaming\\Blackmagic Design\\Fusion\\Modules\\Lua\\?.lua;"`

**Comment by cedricduriau** [comment]
Hi @movalex 

The `/Users/macbuild/` paths are really interesting.. looks like Blackmagic might have kept/left those in for testing purposes.

What concerns the `/usr/local/share/lua/5.1`, it is being read by Fusion, just some undocumented legacy path. So you don't need a local lua, you can just create that path. Same for the env var LUA_PATH.

But considering this all works with the "fallback to self" line of code, I'll add that to the fuse.
@AndrewHazelden: doesn't that match the Resolve atom module import?

Cheers
Cedric

**Comment by AndrewHazelden** [comment]
Hi @cedricduriau.

> But considering this all works with the "fallback to self" line of code, I'll add that to the fuse.
@AndrewHazelden: doesn't that match the Resolve atom module import?

Yes. The Reactor atom packaged version of cryptomatte.fuse did that same code revision 6 months ago. That code snippet can be viewed on [line 15 of the fuse source code](https://gitlab.com/WeSuckLess/Reactor/blob/master/Atoms/com.Psyop.Cryptomatte/Fuses/Matte/cryptomatte.fuse#L15) in the Reactor GitLab Repository:

```
-- add WSL Reactor compatibility to Cryptomatte
local cryptoutils = self and require("cryptomatte_utilities") or nil
```

**Comment by jonahfriedman** [comment]
The fix for this was merged, so I'm going to go ahead and close it.

**Comment by cedricduriau** [comment]
Hi Jonah

Actually no, it's not merged, let me explain.

I created an issue with a dedicated branch on my fork to address this topic. I merged it into my master, but it seems like it was never merged into the main master. I probably forgot, my bad.

If it all works for you, we can merge both. This would then officially solve this issue.

Cheers
Cedric

**Comment by jonahfriedman** [comment]
Ah ok. I'll probably do a new bug fix/performance release soon, so we should merge that in.

**Comment by cedricduriau** [comment]
Ships with 1.4.0, @jonahfriedman feel free to close this one.
