### ISSUE TITLE
Will Cryptomatte eventually be supported in Resolve 15?

### ISSUE THREAD

**Issue by Larkspur89** [Psyop/Cryptomatte#87]
Will Cryptomatte eventually be supported in Resolve 15?

**Comment by cedricduriau** [comment]
Hi @Larkspur89 

Absolutely. Together with @AndrewHazelden we have already explored the required changes, Resolve and Cryptomatte, to make that happen.

To be really honest, it kind of already works, as you will see in Andrew's post on my fork.
He has a patch workflow to make it work for you as we speak.

For a fully working stock Cryptomatte in Resolve, I'd like to hear back from BMD about [my post](https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=77081) on the forum.
If BMD can make what I ask in the post happen, which is really a small fix, then Cryptomatte will be fully working in Resolve. Sadly I haven't had **any** contact with the Resolve guys from BMD so far, which is a shame.

So keep that issue thread on my fork close, that's where I'll be discussing this topic further with Andrew.

Hope that answered your question!

Cheers
Cedric

**Comment by cedricduriau** [comment]
Hi @Larkspur89 

Davince Resolve 15.1 is out and one of the features is the Fusion Loader!
This means that Cryptomatte is from now on available for Resolve!

Check the [release notes](https://www.blackmagicdesign.com/support/readme/3fdf6df340d4452888328ae46ad17e3e) for more info and details of the release.

Cheers
Cedric

**Comment by jonahfriedman** [comment]
That's fantastic news Cedric! We should update documentation and maybe the implementation list. 

Cryptomatte in color grading is something we've been wanting to happen for along time.

**Comment by jonahfriedman** [comment]
Closing this one since this has been out and working for a while now. However we should still update documentation!
