### ISSUE TITLE
Cryptomatte in Nuke 10 is not displaying color cells

### ISSUE THREAD

**Issue by markfatt** [Psyop/Cryptomatte#88]
I just downloaded and installed this on Windows 10.  I can ctrl+select and add geometry, but I never see the color cells.

![image](https://user-images.githubusercontent.com/42589604/44559588-f6114b80-a6ff-11e8-8f29-7c980ccd0e26.png)
 Thanks

**Comment by markfatt** [comment]
So its a feature?  No issue.  I was just looking at an online tutorial and I saw colors.

**Comment by jonahfriedman** [comment]
It's a side effect of a feature. The tutorial must predate the change. 

Glad there's no issue.
