### ISSUE TITLE
Cryptomatte picking up Vray lights in pass

### ISSUE THREAD

**Issue by eoin-vstream** [Psyop/Cryptomatte#89]
I'm getting a strange issue with my Cryptomatte pass in Nuke, I've attached 2 images but as you can see, the Cryptomatte node is picking up the vray lights in my scene and affecting any masks I'm using it with.

![cryptolayer](https://user-images.githubusercontent.com/37383718/44656136-a7113200-a9ef-11e8-986c-4a1c9a3b5b38.JPG)
![original](https://user-images.githubusercontent.com/37383718/44656137-a7113200-a9ef-11e8-994e-350525a097dc.JPG)

The lights are set to be invisible and do not show up in any other passes

Windows 7
3DS Max 2017
Vray 3.6
Nuke 9.0v8

**Comment by vkoylazov** [comment]
If the light is visible, why wouldn't it be picked?

Best regards,
Vlado

**Comment by vkoylazov** [comment]
Ok, I will try to reproduce this here, but in any case it looks like a V-Ray issue and not a Cryptomatte one. If you can email me to vlado@chaosgroup.com with the images and the details, I will ask someone to look into it.

Best regards,
Vlado

**Comment by jonahfriedman** [comment]
Thanks Vlado!
