### ISSUE TITLE
Cryptomatte using Fusion Render Node

### ISSUE THREAD

**Issue by AndrewFromSpaceDeluxe** [Psyop/Cryptomatte#92]
I have gotten Cryptomatte to work in Fusion Studio 9.0.2, and i can render the sequence locally.
I am using Thinkbox Deadline for network rendering and i have installed "Install Fusion Render Node v9.0.2.msi" on my rendernodes.
I first got this error:
INFO: LOG: ...\Roaming\Blackmagic Design\Fusion\Fuses\cryptomatte.fuse:13: module 'cryptomatte_utilities' not found:
INFO: LOG: no field package.preload['cryptomatte_utilities']
INFO: LOG: no file 'LuaModules:cryptomatte_utilities.lua'
INFO: LOG: no file 'LuaModules:cryptomatte_utilities\init.lua'
INFO: LOG: no file 'LuaModules:cryptomatte_utilities.dll'

So i copied the file "cryptomatte.fuse" to folder 
C:\Users\Render\AppData\Roaming\Blackmagic Design\Fusion\Modules\Lua\

and now it renders without error, but my saved images doesn't look right. It looks like the rendernode has completely ignored (or failed) the cryptomatte node.

Has anyone else gotten Cryptomatte to work with Fusion Render Node?

**Comment by jonahfriedman** [comment]
My guess would be that you need a complete installation, not just the fuse. 

Full installation instructions: https://github.com/Psyop/Cryptomatte/blob/master/docs/fusion.md

Can you try that and let us know if that fixes it?

**Comment by cedricduriau** [comment]
Hi @AndrewFromSpaceDeluxe 

First of all, thanks for using Cryptomatte!

Second, the fuse file needs to be in the \Fuses\ directory, the module (*.lua) needs to be in the \Modules\Lua\ directory, please consult the install documentation for a correct installation, as Jonah suggested. When installing everything for Fusion, don't forget to do the same for Fusion Render Node.

And to answer your question, yes somebody else got it to work.
We use and render Cryptomatte daily at Grid, as well through Deadline (10).

Keep us posted!

Cheers
Cedric
