### ISSUE TITLE
i have cryptomatte installed but cant use it

### ISSUE THREAD

**Issue by om2004** [Psyop/Cryptomatte#97]
um i have cryptomattte installed but i cant use it.it does not pickup channels from the file.
![image](https://user-images.githubusercontent.com/44871209/48204124-1b246a80-e38f-11e8-97c7-26e179546387.png)
i used one of your example files.

**Comment by jonahfriedman** [comment]
My guess is the Python components are not installed correctly. Please double check the Nuke installation instructions. 

There's also a troubleshooting button the gizmo that might give you additional clues as to what is wrong. Please let me know if that helps.

**Comment by om2004** [comment]
that solved it thank you

**Comment by jonahfriedman** [comment]
Great to hear it, good luck!
