### ISSUE TITLE
Cryptomatte for Game Engines? Question

### ISSUE THREAD

**Issue by 2daniels** [Psyop/Cryptomatte#98]
Hi!
I hope this is the right place to ask this question. I've been using Cryptomatte for a while now and it has completely changed and improved my production workflows. So far I have been working with Arnold in Maya and Nuke, but we are thinking about an animated short film production using a game engine (unity or unreal) starting soon.
I would love to have the possibility to use Cryptomatte in a game engine. I have some time for rnd so I would love to try to implement this. But before getting into it I wanted to ask if there is already something like that in the making or if you see any major problems heading down that road!
I am thankful for any feedback and feel free to close the ticket if this is the wrong place for this question :D

**Comment by jonahfriedman** [comment]
As far as I know, nobody has done this yet. There is interest in this happening, especially as game engines are used more and more for offline-rendering workflows. I think a lot of people would be very happy for someone to do this, and I don't see any roadblocks beyond figuring out if this is possible in the APIs of the engines.

**Comment by 2daniels** [comment]
Sounds great! I will definitely try to get into this soon!
Thank you very much for the quick reply!

**Comment by jonahfriedman** [comment]
Please feel free to reopen this ticket if there's any news on this front!

**Comment by tanmoycgartist** [comment]
yes that would be really great if we can get cryptogram for game engine. specifically Unreal engine. and after watching the UE5 demo it's more obvious now.
